---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      gui: true
      customize:
        memory: 2048
        vram: 256
        usb: 'on'
        usbxhci: 'on'
#  Issue with USB filter Vagrant Option proccessing correctly in Kitchen yml file.
#    usbfilter:
#      - name: 'Movidius MA2X5X [0001]'
#        vendorid: '03E7'

suites:
  - name: default
    run_list:
      - recipe[MovidiusNCSDK::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
